version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c 'yarn && yarn dev'
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - 8080:3000
    environment:
      - NODE_ENV=development
    tty: true
    networks:
      - restapi-todo-nestjs_default

volumes:
  frontend_node_modules:

networks:
  restapi-todo-nestjs_default:
    external: true
